version: '3'
services:
  keycloak:
    container_name: keycloak-server
    image: jboss/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin