version: '3.9'
services:
  keycloak:
    container_name: keycloak-server
    build: 
      context: github.com/keycloak/keycloak-containers.git#16.1.0:server
    image: jboss/keycloak:16.1.0
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/data.json
    volumes:
      - ./data/test-realm.json:/tmp/data.json
