version: '3.9'
services:
  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:19.0.1-legacy
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/data.json
    volumes:
      - ./data/test-realm.json:/tmp/data.json
